questions = {
    # No : [ Question, [reponse1,réponse2...], QCU?QCM]   : False pour pour QCM et True pour QCU
    1 : ["Question Vrai / Faux", 
		["Vrai", "Faux"],
		True],
	2 : ["Question Oui / Non", 
		["Oui", "Non"],
		True],
	3 : ["Choix unique A B C D", 
		["Réponse A", "Réponse B", "Réponse C", "Réponse D"],
		True],
	4 : ["Choix multiple QCM A B C D", 
		["Réponse A", "Réponse B", "Réponse C", "Réponse D"],
		False],
	5 : ["Quelle est la relation entre énergie d'un photon et fréquence de l'onde associée ?", 
		[" \(E = h \\nu \) ", " \(E = h + \\nu \) ", " \(E = \dfrac{h}{\\nu} \) "],
		True],
	6 : ["Quelle est la relation entre la quantité de mouvement d'un photon et la longueur d'onde de l'onde associée ?", 
		[" \(p = h \lambda \) ", " \(p = h + \lambda \) ", " \(p = \dfrac{h}{\lambda} \) "],
		True],
	7 : ["Quelle est la relation entre la longueur d'onde de l'onde associée à un électron, sa masse et sa vitesse ?", 
		[" \(\lambda = h m v  \) ", " \(\lambda = \dfrac{h}{mv} \) ", " \(\lambda = \dfrac{mv}{h} \) "],
		True],
	8 : ["Quelle est la relation entre la longueur d'onde de l'onde associée à un électron, sa masse et sa vitesse ?", 
		[" \(\lambda = h m v  \) ", " \(\lambda = \dfrac{h}{mv} \) ", " \(\lambda = \dfrac{mv}{h} \) "],
		True],
	9 : ["Conversion énergie électron-Volt, Joule :", 
		[" \(1 eV = 1,6.10^{-19} J   \) ", " \(1 J = 1,6.10^{-19} eV   \)  ", " 1 eV c'est beaucoup de Joules", " 1 Joule c'est beaucoup d'eV ", " l'eV est adapté au niveau microscopique ", " l'eV est adapté au niveau macroscopique "], 
		False],    
}
